# Generated by Django 4.2.3 on 2023-08-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reachme',
            old_name='fname',
            new_name='name',
        ),
    ]
